server {
  host = "0.0.0.0"
  port = 8080
}

database {
  # Default to localhost for local development with sbt run
  url = "jdbc:postgresql://localhost:5432/homeworker"
  # Override with db host when running in Docker
  url = ${?DB_URL}
  user = "postgres"
  user = ${?DB_USER}
  password = "postgres"
  password = ${?DB_PASSWORD}
  driver = "org.postgresql.Driver"
}

auth {
  secret-key = "your-secret-key-here"
  secret-key = ${?AUTH_SECRET_KEY}
  token-expiration = 60 # minutes
} 